name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set buildtime
      run: echo "builddate=$(date +%s)" >> "$GITHUB_ENV"
    - name: Build the Docker image grafana_api_data
      run: docker build ./curl --tag flx5/intro-to-mltp:grafana_api_data-${builddate}
    - name: Build the Docker image mythical-beasts-requester
      run: docker build ./source -f ./source/docker/Dockerfile --build-arg SERVICE=mythical-beasts-requester --tag flx5/intro-to-mltp:mythical-beasts-requester-${builddate}
    - name: Build the Docker image mythical-beasts-server
      run: docker build ./source -f ./source/docker/Dockerfile --build-arg SERVICE=mythical-beasts-server --tag flx5/intro-to-mltp:mythical-server-${builddate}
    - name: Build the Docker image mythical-beasts-recorder
      run: docker build ./source -f ./source/docker/Dockerfile --build-arg SERVICE=mythical-beasts-recorder --tag flx5/intro-to-mltp:mythical-recorder-${builddate}
    - name: Login
      run: echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
      env: # Or as an environment variable
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
    - name: Publish  grafana_api_data
      run: docker push -a flx5/intro-to-mltp
